baseURL: https://agonzalezro.github.io
languageCode: en-us
title: // Álex Go{,5z}
theme: hello-friend-ng

services:
  googleAnalytics:
    id: 363076712 # UA-35984509-1

paginate: 9999 # Let's call it infinite

params:
  rssFullText: true

  rss:
    authorName: Álex González
    authorEmail: agonzalezro@gmail.com

  showReadingTime: true
  disableReadOtherPosts: true
  enableSharingButtons: false
  enableGlobalLanguageMenu: false
  enableThemeToggle: true
  logo:
    logoMark: ""

languages:
  en:
    params:
      dateFormatSingle: "02-01-2006" 
      dateFormatList: "02-01-2006"
      logo:
        logoMark: " "
        logoText: "// Álex Go{,5z}"
        logoCursorDisabled: true

